name: Checks

on:
  pull_request:
    paths:
      - '.github/workflows/checks.yml'
      - '__tests__/**'
      - 'src/**'
      - 'jest.config.js'
      - 'package-lock.json'

jobs:
  test:
    name: tests
    runs-on: ubuntu-latest
    if: |
      !contains(github.event.head_commit.message, '[skip ci]')
    permissions:
      checks: write
      pull-requests: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install NPM Dev Dependencies
        run: |
          npm ci
      
      - name: Run Tests and Check Coverage
        uses: ArtiomTr/jest-coverage-report-action@v2
