# .github/workflows/test-action.yml
name: Test Action

on:
  pull_request:
    branches: [master, main]

jobs:
  argocd-diff:
    name: Generate ArgoCD Diff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Build dist
        run: |
          npm ci
          npx ncc build --source-map

      - uses: ./
        with:
          argocd-server-fqdn: wn6bfwa9q1wk9mhq.cd.akuity.cloud
          argocd-token: ${{ secrets.ARGOCD_TOKEN }}
          github-token: ${{ secrets.GH_MOREY_TECH_BOT_TOKEN }}
          argocd-extra-cli-args: --grpc-web
          argocd-exclude-paths: "path/to/exclude,"